pipelines:
  branches:
    develop:
      - step:
          name: Build images development
          image: node:16.18.0
          services:
            - docker
          caches:
            - node
          script:
            - cp .env.example .env
            - npm install
            - npm run build
            - export BUILD_ID=$BITBUCKET_BRANCH_$BITBUCKET_COMMIT_$BITBUCKET_BUILD_NUMBER
            - export IMAGE_NAME=${KBS_REGISTRY_URL}/kbs-dashboard/pms:latest-dev
            - export USER=$DOCKER_USERNAME
            - export PASS=$DOCKER_PASSWORD
            - docker login ${KBS_REGISTRY_URL} -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
            - docker build -f ./Dockerfile -t $IMAGE_NAME .
            - docker push $IMAGE_NAME
          

            
      - step:
          name: Deployment Development
          image: ragilkbs/kbs-digital:latest
          script:
            - export IMAGE_NAME=${KBS_REGISTRY_URL}/kbs-dashboard/pms:latest-dev
            - export SSHPASS=$SSH_PASSWORD
            - sshpass -p $SSHPASS ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST_DEV "cd $SCRIPTS; pwd; docker-compose down; docker stop pms-dev_laravel.pms_1; docker rm pms-dev_laravel.pms_1; docker rmi $IMAGE_NAME; docker pull $IMAGE_NAME; docker-compose up -d"
            - echo "Deployment Development done"

            
definitions:
  services:
    docker:
      memory: 2048 # reduce memory for docker-in-docker from 1GB to 512MB


options: